config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'

  devise_for :users
  root to: 'pages#home'
  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :broadcast_to_post_show

  private

  def broadcast_to_post_show
    ActionCable.server.broadcast(
      "post_#{self.post.id}",
      comment: ApplicationController.new.render_to_string(partial: 'comments/comment', locals: { comment: self })
    )
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  after_save :broadcast_to_index

  private

  def broadcast_to_index
    ActionCable.server.broadcast(
      'index',
      post: ApplicationController.new.render_to_string(
        partial: 'posts/post',
        locals: {
          post: self,
          path: Rails.application.routes.url_helpers.post_path(self, locale: nil)
        },
        layout: false)
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])

    comment = Comment.new(comment_params.merge!(post: @post, user: current_user))
    if comment.save
      redirect_to @post
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @posts = Post.all.order(created_at: :DESC)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.includes(:comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge!(user: current_user))
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-author">
    <%= comment.user.email %> at <%= comment.created_at.strftime('%H:%M') %>
  </div>
  <%= comment.text %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for [@post, @comment] do |f| %>
        <div class="row">
          <div class="col">
            <%= f.input :text %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.button :submit, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= link_to 'New post', new_post_path, class: 'new-link btn btn-primary' %>
      <% if @posts.any? %>
        <div class="posts">
          <% @posts.each do |post| %>
            <%= render 'posts/post', post: post %>
          <% end %>
        </div>
      <% else %>
        <p>no posts yet</p>
      <% end %>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
  <script type="text/javascript">
    App.cable.subscriptions.create(
      {
        channel: "IndexChannel"
      },
      {
        connected: function(data) {
          console.log("connected to index channel");
        },
        received: function(data) {
          $(".posts").prepend(data["post"]);
          $(".post").first().hide().slideDown();
        }
      }
    )
  </script>
<% end %>

app/views/posts/_post.html.erb
<p class="post"><%= link_to post.title, local_assigns[:path] ? path : post %> (
<span><%= post.comments.length %></span>
)</p>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for @post do |f| %>
        <div class="row">
          <div class="col">
            <%= f.input :title %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.input :text %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.button :submit, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="post">
        <div class="post-title">
          <h1><%= @post.title %></h1>
        </div>
        <div class="post-text">
          <%= @post.text %>
        </div>
        <div class="post-comments">
          <%= link_to 'New comment', new_post_comment_path(@post), class: 'btn btn-primary' %>
          <% if @post.comments.any? %>
            <div class="post-comments-container">
              <% @post.comments.order(created_at: :DESC).each do |comment| %>
                  <%= render 'comments/comment', comment: comment %>
              <% end %>
            </div>
          <% else %>
            <div class="comment">
              <p>no comments yet !</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
  <script type="text/javascript">
    App.cable.subscriptions.create(
      {
        channel: "PostChannel",
        post_id: <%= @post.id %>
      },
      {
        connected: function(data) {
          console.log("connected to post_<%= @post.id %>");
        },
        received: function(data) {
          $(".post-comments-container").prepend(data["comment"]);
          $(".comment").first().hide().slideDown();
        }
      }
    )
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>